version: "3.4"
services:
    web:
        image: smartstore
        container_name: web
        ports:
            - "80:80"
        depends_on:
            - db
        volumes:
            - "D:/mount/smtenants/mysql:/app/App_Data/Tenants"
    db:
        image: mysql
        container_name: mysql
        environment:
            #MYSQL_DATABASE: smartstore
            #MYSQL_USER: "root"
            MYSQL_PASSWORD: "Smartstore2022!"
            MYSQL_ROOT_PASSWORD: "Smartstore2022!"
        ports:
          - '3307:3306'
        expose:
          - '3306'
        volumes:
          - mysql:/var/lib/mysql

volumes:
  mysql: